services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file: "./.env"
  flask: 
    build: 
      context: .
      dockerfile: ./backend/Dockerfile 
    ports:
      - "5000:5000"
    depends_on: 
      - postgres 
  
  
