services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file: "./.env"
  flask: 
    build: 
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app 
    depends_on: 
      - db 
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app  
      - /usr/src/app/node_modules  
    depends_on:
      - db 
      - flask 

    
 
  
  
